name: Compile on ubuntu

on: [push]

jobs:
  ubuntu:
    name: Compile
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Install deps
        run: sudo apt-get install libpcap-dev -y
      - run: autoreconf -i
      - run: ./configure
      - run: make
      - run: make dist
      - name: Upload package
        uses: actions/upload-artifact@v2
        with:
          name: package
          path: namescan-*.tar.gz
